get: 
  tags: 
    -  Product
  summary: Get a product by its ID
  description: Get a product by its ID.
  operationId: getProductById
  parameters: 
    - $ref: ../../components/parameters/v1/product_id.yaml
  responses:
    '200': 
      description: Success
      content: 
        application/json: 
          schema: 
            $ref: ../../components/schemas/v1/product.yaml
    '400':
      description: Bad Request
      content: 
        application/json: 
          schema: 
            $ref: ../../components/schemas/Problem.yaml
    '404':
      description: Not Found
      content: 
        application/json: 
          schema: 
            $ref: ../../components/schemas/Problem.yaml