name: API Linting with Redocly

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-node@v4
        name: Setup Node 18
        with:
          node-version: 18
      - run: npm install -g @redocly/cli@latest
        name: Install Redocly CLI
      - run: redocly lint openapi/openapi.yaml --format=github-actions
            
