name: Build and Deploy API Docs

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - name: Grant execute permission to make.sh
        run: chmod +x ./make.sh
      - name: Build Docs
        run: ./make.sh
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,openapi,.redocly.yaml,make.sh'
          