name: Build and Deploy API Documentation

on:
  push:
    branches:
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - run: ./make.sh
        name: Build API Documentation
      - uses: peaceiris/actions-gh-pages@v4
        name: Deploy to GitHub Pages
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,openapi,.redocly.yaml,make.sh'
          